### ISSUE TITLE
Pretrained models are not accessible

### ISSUE THREAD

**Issue by denizubu** [fanjunkai1/DVD#4]
Hi! When I click the download links, it says this page does not exist anymore. Also, I couldn't find remove_hazy_model_256x256.pth that mentioned in inference command. Thanks in advance.

**Comment by fanjunkai1** [comment]
Thanks for your attention!
I tried clicking the download link and didn't find any issues.

**Comment by fanjunkai1** [comment]
> Hi! When I click the download links, it says this page does not exist anymore. Also, I couldn't find remove_hazy_model_256x256.pth that mentioned in inference command. Thanks in advance.

Thanks for your attention!
I tried clicking the download link and didn't find any issues.

**Comment by denizubu** [comment]
> > Hi! When I click the download links, it says this page does not exist anymore. Also, I couldn't find remove_hazy_model_256x256.pth that mentioned in inference command. Thanks in advance.
> 
> Thanks for your attention! I tried clicking the download link and didn't find any issues.

Thanks for your reply. I realized that I can't download Baidu links, since either Baidu banned my country or my country banned it. Can you provide any other link or should I try to find a way around?

**Comment by fanjunkai1** [comment]
> > > Hi! When I click the download links, it says this page does not exist anymore. Also, I couldn't find remove_hazy_model_256x256.pth that mentioned in inference command. Thanks in advance.
> > 
> > 
> > Thanks for your attention! I tried clicking the download link and didn't find any issues.
> 
> Thanks for your reply. I realized that I can't download Baidu links, since either Baidu banned my country or my country banned it. Can you provide any other link or should I try to find a way around?

You can download the pre-trained model by clicking the following link: [click here](https://drive.google.com/drive/folders/191tmi1NTMSFyTFxC0ap81h54MXM5OY6x?dmr=1&ec=wgc-drive-globalnav-goto)

**Comment by denizubu** [comment]
> > > > Hi! When I click the download links, it says this page does not exist anymore. Also, I couldn't find remove_hazy_model_256x256.pth that mentioned in inference command. Thanks in advance.
> > > 
> > > 
> > > Thanks for your attention! I tried clicking the download link and didn't find any issues.
> > 
> > 
> > Thanks for your reply. I realized that I can't download Baidu links, since either Baidu banned my country or my country banned it. Can you provide any other link or should I try to find a way around?
> 
> You can download the pre-trained model by clicking the following link: [click here](https://drive.google.com/drive/folders/191tmi1NTMSFyTFxC0ap81h54MXM5OY6x?dmr=1&ec=wgc-drive-globalnav-goto)

Thank you! Great work by the way.
